version: "3.8"

services:
  db:
    image: postgres:17
    container_name: poc-db
    environment:
      POSTGRES_USER: pocuser
      POSTGRES_PASSWORD: pocpassword
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clj-fullstack-app
    ports:
      - "3000:3000" # Adjust the host port as needed
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/poc_db"
      DB_USER: pocuser
      DB_PASSWORD: pocpassword
    depends_on:
      - db

volumes:
  db_data:
